import { notFound, redirect } from "next/navigation";
import Link from "next/link";
import { FEATURES } from "@/lib/config/features";
import { createClient } from "@/lib/supabase/server";
import { benchmarkCatalogSchema } from "../benchmarks/catalog";

export default async function ComparisonsPage(){
  if(!FEATURES.eliteBenchmarkEngine||!FEATURES.comparisonDeveloperUi)notFound();
  const supabase=await createClient(),{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
  const{data,error}=await supabase.rpc("get_benchmark_developer_catalog");if(error)notFound();
  const parsed=benchmarkCatalogSchema.safeParse(data);if(!parsed.success)notFound();
  const datasets=parsed.data.datasets.filter(item=>item.active&&item.verified);
  return <main className="ava-carbon min-h-screen p-6 text-white"><div className="mx-auto max-w-7xl"><Link href="/benchmarks" className="text-sm text-[#b3bccb]">← Benchmark catalog</Link><header className="mt-7"><p className="text-xs font-bold uppercase tracking-[.24em] text-[#2f80ed]">Comparison visualization laboratory</p><h1 className="mt-2 text-3xl font-semibold">Compatible comparisons</h1><p className="mt-2 text-[#b3bccb]">Distribution curves and percentile landmarks render only from active verified records.</p></header>{datasets.length?<div className="mt-8 grid gap-6 lg:grid-cols-2">{datasets.flatMap(dataset=>dataset.contract.entries.map(entry=><article key={`${dataset.id}:${entry.entryId}`} className="rounded-2xl border border-white/10 bg-[#101827] p-5"><h2 className="font-semibold">{dataset.contract.datasetName}</h2><p className="mt-1 text-xs text-[#7e8797]">{entry.metric} · {entry.event} · {entry.phase} · {entry.sex}</p><Distribution percentiles={entry.percentiles}/><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><Stat label="Median" value={entry.median}/><Stat label="Mean" value={entry.mean}/><Stat label="SD" value={entry.standardDeviation}/></div></article>))}</div>:<section className="mt-8 grid gap-4 md:grid-cols-2"><Placeholder title="Percentiles and distribution curves"/><Placeholder title="Radar and similarity map"/><Placeholder title="Personal and season trend lines"/><Placeholder title="Fingerprint comparison"/></section>}<p className="mt-8 rounded-xl border border-[#f5c451]/30 bg-[#f5c451]/10 p-4 text-sm text-[#f5c451]">No valid percentile is shown when protocol, metric definition, timing, FPS, event, phase, or population compatibility fails.</p></div></main>
}
function Distribution({percentiles}:{percentiles:Record<number,number>}){const points=Object.entries(percentiles).map(([p,v])=>[Number(p),v] as const).sort((a,b)=>a[0]-b[0]);if(points.length<2)return <p className="mt-5 text-sm text-[#7e8797]">No distribution curve available.</p>;const values=points.map(p=>p[1]),min=Math.min(...values),max=Math.max(...values),range=max-min||1;const path=points.map(([p,v],i)=>`${i?"L":"M"} ${p} ${90-((v-min)/range)*70}`).join(" ");return <svg viewBox="0 0 100 100" role="img" aria-label="Benchmark percentile distribution curve" className="mt-5 h-44 w-full rounded-xl bg-black/20 p-2"><path d={path} fill="none" stroke="#2f80ed" strokeWidth="2"/><line x1="0" y1="90" x2="100" y2="90" stroke="#555"/>{points.map(([p,v])=><circle key={p} cx={p} cy={90-((v-min)/range)*70} r="2" fill="#f5f7fb"><title>{p}th percentile: {v}</title></circle>)}</svg>}
function Stat({label,value}:{label:string;value:number|null}){return <div className="rounded-lg bg-white/[.035] p-3"><p className="text-[#7e8797]">{label}</p><p className="mt-1 text-white">{value??"—"}</p></div>}
function Placeholder({title}:{title:string}){return <div className="rounded-2xl border border-dashed border-white/10 p-6"><h2 className="font-semibold">{title}</h2><p className="mt-2 text-sm text-[#7e8797]">Awaiting a compatible verified dataset; no demonstration values are fabricated.</p></div>}

