import { notFound, redirect } from "next/navigation";
import { FEATURES } from "@/lib/config/features";
import { createClient } from "@/lib/supabase/server";
import type { CoachingFocus } from "@/lib/adaptiveCoaching";
import { cachedCoachingStateSummarySchema } from "./catalog";

export default async function CoachingPage({searchParams}:{searchParams:Promise<{athleteId?:string}>}){
  if(!FEATURES.adaptiveCoachingEngine||!FEATURES.adaptiveCoachingDashboard)notFound();
  const{athleteId}=await searchParams;if(!athleteId)notFound();
  const supabase=await createClient(),{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
  const{data,error}=await supabase.rpc("get_cached_coaching_state",{p_athlete_id:athleteId});if(error)notFound();
  const parsed=cachedCoachingStateSummarySchema.safeParse(data);if(!parsed.success)notFound();
  const state=parsed.data.activeState;
  return <main className="ava-carbon min-h-screen p-6 text-white"><div className="mx-auto max-w-6xl"><header><p className="text-xs font-bold uppercase tracking-[.24em] text-[#2f80ed]">Cached coaching intelligence</p><h1 className="mt-2 text-3xl font-semibold">Adaptive Coaching State</h1><p className="mt-2 text-[#b3bccb]">This page reads the precomputed state. It never evaluates the athlete on page open.</p></header>{state?<div className="mt-8 space-y-6"><section className="grid gap-4 md:grid-cols-3"><Stat label="Confidence" value={`${state.coachingConfidence.level} · ${state.coachingConfidence.score}/100`}/><Stat label="Freshness" value={state.dataFreshness.status}/><Stat label="Pending invalidations" value={String(parsed.data.pendingInvalidations)}/></section><section className="grid gap-6 lg:grid-cols-2"><Panel title="Primary focus">{state.currentPrimaryFocus?<Focus focus={state.currentPrimaryFocus}/>:<Empty/>}</Panel><Panel title="Secondary focus">{state.secondaryFocuses.length?state.secondaryFocuses.map(focus=><Focus key={focus.focusId} focus={focus}/>):<Empty/>}</Panel><Panel title="Maintenance">{state.maintenanceFocuses.length?state.maintenanceFocuses.map(focus=><Focus key={focus.focusId} focus={focus}/>):<Empty/>}</Panel><Panel title="Monitoring">{state.monitoringFocuses.length?state.monitoringFocuses.map(focus=><Focus key={focus.focusId} focus={focus}/>):<Empty/>}</Panel><Panel title="Retired priorities">{state.retiredPriorities.length?state.retiredPriorities.map(focus=><Focus key={focus.focusId} focus={focus}/>):<Empty/>}</Panel><Panel title="Competition and season"><p className="text-sm text-[#b3bccb]">{state.seasonContext.stage.replaceAll("_"," ")} · {state.seasonContext.daysToCompetition??"No"} days to competition</p>{state.competitionAdjustments.map(item=><p key={item.candidateId} className="mt-2 text-xs text-[#f5c451]">{item.reason}</p>)}</Panel></section><p className="text-xs text-[#7e8797]">{state.engineVersion} · zero external model calls · {parsed.data.stateHistory.length} cached version(s)</p></div>:<section className="mt-8 rounded-2xl border border-dashed border-white/10 p-8"><h2 className="font-semibold">No cached CoachingState</h2><p className="mt-2 text-sm text-[#7e8797]">A server evaluation must be triggered by finalized structured intelligence. No coaching focus is fabricated.</p></section>}</div></main>
}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white/10 bg-[#182233] p-4"><p className="text-xs text-[#7e8797]">{label}</p><p className="mt-2 font-semibold">{value}</p></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-white/10 bg-[#101827] p-5"><h2 className="mb-3 font-semibold">{title}</h2>{children}</section>}
function Focus({focus}:{focus:CoachingFocus}){return <article className="mb-3 rounded-xl bg-white/[.035] p-4"><p className="font-semibold">{focus.title}</p><p className="mt-1 text-sm text-[#b3bccb]">{focus.objective}</p><p className="mt-2 text-xs text-[#7e8797]">{focus.explanation}</p></article>}
function Empty(){return <p className="text-sm text-[#7e8797]">No eligible stored focus.</p>}
