import type { RecommendationTemplate } from "./types";

const t = (value: RecommendationTemplate): RecommendationTemplate => value;

export const RECOMMENDATION_LIBRARY = {
  projection: t({
    key: "projection_without_reaching", category: "technical_focus",
    title: "Improve projection without reaching",
    summary: "Emphasize forward displacement while preserving rhythm and natural touchdown position.",
    guidance: ["Use projection-focused technical buildups; a coach may also consider short hills or resisted accelerations."],
    cues: ["Project the hips forward", "Avoid reaching", "Preserve relaxation"],
    caution: "Do not force a longer step. The target is organization and force direction, not reaching farther.",
  }),
  reduceReaching: t({
    key: "touchdown_without_reaching", category: "technical_focus",
    title: "Review touchdown organization",
    summary: "Preserve rhythm and posture while reviewing whether step placement is occurring naturally.",
    guidance: ["Use controlled buildups or naturally spaced wickets to review touchdown position."],
    cues: ["Step down beneath the body", "Stay tall through the zone", "Preserve rhythm"],
    caution: "Step length above an expectation does not, by itself, confirm overstriding.",
  }),
  recoveryRhythm: t({
    key: "recovery_and_upright_rhythm", category: "rhythm_focus",
    title: "Improve recovery timing and upright rhythm",
    summary: "Explore quicker, relaxed recovery without sacrificing posture or displacement.",
    guidance: ["Consider short fly exposures, dribble series, or controlled wicket runs."],
    cues: ["Recover forward smoothly", "Preserve relaxation", "Keep posture controlled"],
    caution: "Do not chase cadence by shortening the step or tensing the upper body.",
  }),
  preserveDisplacement: t({
    key: "preserve_turnover_improve_displacement", category: "technical_focus",
    title: "Preserve turnover while improving displacement",
    summary: "Keep the available rhythm while exploring better projection and natural step length.",
    guidance: ["Use controlled buildups or wickets with spacing that encourages natural displacement."],
    cues: ["Keep the rhythm", "Project forward", "Avoid choppy steps"],
    caution: "High frequency is not automatically positive or negative; compare it at a matched velocity.",
  }),
  lengthAssessment: t({
    key: "horizontal_force_assessment", category: "assessment",
    title: "Assess horizontal-force qualities",
    summary: "Physical testing may help distinguish force production, timing, mobility, and normal variation.",
    guidance: ["A coach may compare horizontal jump, unilateral strength, or force-testing results with repeated video."],
    cues: [], conditional: true, requiresCoachReview: true, requiresPhysicalTesting: true,
    caution: "Sprint footage cannot determine strength, mobility, tissue capacity, or injury status.",
  }),
  reactiveAssessment: t({
    key: "reactive_strength_assessment", category: "assessment",
    title: "Assess reactive-strength and contact-time qualities",
    summary: "Additional testing may clarify whether physical qualities are associated with the observed rhythm.",
    guidance: ["Consider contact-time or reactive-strength testing and higher-frame-rate video."],
    cues: [], conditional: true, requiresCoachReview: true, requiresPhysicalTesting: true,
    caution: "Footage alone cannot establish an elasticity, stiffness, or strength deficit.",
  }),
  sideReview: t({
    key: "side_specific_technical_review", category: "technical_focus",
    title: "Review left–right touchdown and recovery",
    summary: "Compare side-specific touchdown position, recovery timing, and rhythm before selecting a corrective action.",
    guidance: ["Use controlled bilateral technical runs and side-by-side coach review."],
    cues: ["Keep left–right timing even", "Maintain relaxed recovery"],
    caution: "A side difference does not establish weakness, injury, or its cause.",
    requiresCoachReview: true,
  }),
  unilateralAssessment: t({
    key: "unilateral_assessment", category: "assessment",
    title: "Add a unilateral physical comparison",
    summary: "Testing may help distinguish force, mobility, timing, and normal side-to-side variation.",
    guidance: ["Consider unilateral jump or strength testing and an ankle, knee, hip, and pelvic review."],
    cues: [], conditional: true, requiresCoachReview: true, requiresPhysicalTesting: true,
    caution: "Do not diagnose the lower-displacement or slower side as weak or injured from video.",
  }),
  asymmetryMonitor: t({
    key: "monitor_asymmetry", category: "monitoring",
    title: "Confirm the side-to-side pattern",
    summary: "Repeat the same measured zone to determine whether the direction and size of the difference persist.",
    guidance: ["Compare at least three compatible sessions, including a fresh condition when practical.", "Verify side labels and sample counts."],
    cues: [], caution: "A single session is not enough to establish a trend.",
  }),
  resistedProjection: t({
    key: "resisted_projection", category: "resisted_sprint",
    title: "Consider a projection-focused sprint direction",
    summary: "Short resisted accelerations or hills may reinforce projection and horizontal force direction.",
    guidance: ["Use this as a direction for coach-selected exposure, not an exact load or volume prescription."],
    cues: ["Push the ground back", "Project the hips forward"], conditional: true, requiresCoachReview: true,
    caution: "Do not infer a strength deficit from the sprint footage.",
  }),
  combinedOrganization: t({
    key: "combined_velocity_organization", category: "technical_focus",
    title: "Prioritize one organization constraint",
    summary: "Improve sprint organization and velocity without chasing step length and frequency simultaneously.",
    guidance: ["A coach should select one primary technical focus, then reassess both metrics."],
    cues: ["Stay organized", "Preserve relaxation"], requiresCoachReview: true,
    caution: "Avoid making simultaneous major changes to both length and frequency.",
  }),
  velocityConsistency: t({
    key: "velocity_consistency_monitor", category: "monitoring",
    title: "Monitor velocity consistency",
    summary: "Repeat a comparable or longer measured zone before interpreting a peak-to-average gap.",
    guidance: ["Review whether one unusually fast interval affected peak velocity and compare compatible sessions."],
    cues: [], caution: "One short measured zone cannot diagnose speed endurance.",
  }),
  broadAssessment: t({
    key: "broader_mechanics_assessment", category: "assessment",
    title: "Add a broader sprint-mechanics assessment",
    summary: "The current evidence does not isolate one change target confidently.",
    guidance: ["Collect higher-frame-rate video and qualified coach review before changing training."],
    cues: [], conditional: true, requiresCoachReview: true,
    caution: "Missing evidence should not be replaced with a physical diagnosis.",
  }),
} as const;
