/**
 * Research knowledge base (Phase 8) — CONFIGURABLE structured store + tagging config.
 *
 * IMPORTANT: the entries below are ILLUSTRATIVE SEED DATA that exercise the engine's
 * structure — they use placeholder authors/journals ("Seed Data") and are NOT real
 * citations or claims. Future ingestion (peer-reviewed papers, textbooks, consensus
 * statements, systematic reviews, meta-analyses, internal validation) replaces them
 * through the source-tracking/versioning/approval seams on `ResearchPaper`.
 */

import type { ResearchPaper } from "./models";

export const RESEARCH_KB_VERSION = "ava-research-kb-v1-seed" as const;

/** Keyword → tag maps used to auto-tag a paper from its text. */
export const METRIC_KEYWORDS: Record<string, string> = {
  "stride length": "strideLength",
  "step length": "strideLength",
  "stride frequency": "strideFrequency",
  "step frequency": "strideFrequency",
  cadence: "strideFrequency",
  "ground contact": "groundContactTime",
  "contact time": "groundContactTime",
  "flight time": "flightTime",
  "peak velocity": "peakVelocity",
  "maximum velocity": "peakVelocity",
  "top speed": "peakVelocity",
  acceleration: "acceleration",
};
export const INTERVENTION_KEYWORDS: Record<string, string> = {
  "flying sprint": "flyingSprints",
  "resisted sprint": "resistedAccelerations",
  "resisted acceleration": "resistedAccelerations",
  "hill sprint": "hillAccelerations",
  wicket: "wicketRuns",
  bound: "alternateBounds",
  plyometric: "pogoSeries",
  "depth jump": "depthJumps",
  "drop jump": "dropJumps",
};
export const ROOT_CAUSE_KEYWORDS: Record<string, string> = {
  "reactive strength": "reactiveStrength",
  stiffness: "elasticStiffness",
  "front-side": "frontSideMechanics",
  projection: "projection",
  "vertical force": "verticalForce",
  "horizontal force": "verticalForce",
};
export const CHARACTERISTIC_KEYWORDS: Record<string, string> = {
  sprinter: "trained_sprinter",
  elite: "elite",
  collegiate: "collegiate",
  female: "female",
  male: "male",
  "100m": "100m",
  "200m": "200m",
  "400m": "400m",
};

const SEED = "seed-v1";

export const RESEARCH_PAPERS: ResearchPaper[] = [
  {
    id: "fly_maxvel_1",
    title: "Flying sprint exposures and maximum velocity mechanics in trained sprinters",
    authors: ["Seed Data"],
    publication: "AVA Seed Knowledge Base",
    year: 2021,
    journal: "Seed Data",
    sport: "athletics",
    population: { sex: "M", event: "100m", performanceLevel: "advanced", sampleSize: 24, anthropometricNote: "trained male sprinters" },
    studyType: "cohort",
    quality: "moderate",
    keyFindings: ["Flying sprint work was associated with improved peak velocity and stride length."],
    limitations: ["Modest sample", "no long-term follow-up"],
    supportedMetrics: ["peakVelocity", "strideLength"],
    supportedInterventions: ["flyingSprints"],
    supportedConclusions: ["Flying sprints are commonly used to develop maximum velocity mechanics."],
    citation: "Seed Data (2021). AVA Seed Knowledge Base.",
    tags: { metrics: [], interventions: [], rootCauses: [], characteristics: [] },
    stanceByTarget: { flyingSprints: "supporting", peakVelocity: "supporting" },
    sourceVersion: SEED,
    approved: true,
  },
  {
    id: "fly_maxvel_2",
    title: "Maximum velocity training review: flying runs and top speed",
    authors: ["Seed Data"],
    publication: "AVA Seed Knowledge Base",
    year: 2019,
    journal: "Seed Data",
    sport: "athletics",
    population: { sex: "mixed", event: "sprint", performanceLevel: "mixed", sampleSize: 120, anthropometricNote: "mixed sprinters" },
    studyType: "systematic_review",
    quality: "strong",
    keyFindings: ["Consistent association between flying-run exposure and top-speed mechanics."],
    limitations: ["Heterogeneous protocols"],
    supportedMetrics: ["peakVelocity"],
    supportedInterventions: ["flyingSprints"],
    supportedConclusions: ["Flying sprints commonly develop maximum velocity."],
    citation: "Seed Data (2019). AVA Seed Knowledge Base.",
    tags: { metrics: [], interventions: [], rootCauses: [], characteristics: [] },
    stanceByTarget: { flyingSprints: "supporting" },
    sourceVersion: SEED,
    approved: true,
  },
  {
    id: "fly_mixed_1",
    title: "Individual variation in response to flying sprint volume",
    authors: ["Seed Data"],
    publication: "AVA Seed Knowledge Base",
    year: 2020,
    journal: "Seed Data",
    sport: "athletics",
    population: { sex: "F", event: "100m", performanceLevel: "advanced", sampleSize: 16, anthropometricNote: "female sprinters" },
    studyType: "cohort",
    quality: "limited",
    keyFindings: ["Responses to flying sprint volume varied; some athletes showed little change."],
    limitations: ["Small sample", "short duration"],
    supportedMetrics: ["peakVelocity"],
    supportedInterventions: ["flyingSprints"],
    supportedConclusions: ["Individual responses vary."],
    citation: "Seed Data (2020). AVA Seed Knowledge Base.",
    tags: { metrics: [], interventions: [], rootCauses: [], characteristics: [] },
    stanceByTarget: { flyingSprints: "neutral" },
    sourceVersion: SEED,
    approved: true,
  },
  {
    id: "plyo_reactive_1",
    title: "Plyometric training and reactive strength / ground contact",
    authors: ["Seed Data"],
    publication: "AVA Seed Knowledge Base",
    year: 2018,
    journal: "Seed Data",
    sport: "athletics",
    population: { sex: "mixed", event: "sprint", performanceLevel: "intermediate", sampleSize: 60, anthropometricNote: "trained athletes" },
    studyType: "meta_analysis",
    quality: "strong",
    keyFindings: ["Plyometrics associated with reduced ground contact and improved reactive strength."],
    limitations: ["Varied plyometric doses"],
    supportedMetrics: ["groundContactTime"],
    supportedInterventions: ["pogoSeries", "depthJumps", "dropJumps", "straightLegBounds"],
    supportedConclusions: ["Plyometrics commonly develop reactive strength."],
    citation: "Seed Data (2018). AVA Seed Knowledge Base.",
    tags: { metrics: [], interventions: [], rootCauses: [], characteristics: [] },
    stanceByTarget: { pogoSeries: "supporting", depthJumps: "supporting", groundContactTime: "supporting" },
    sourceVersion: SEED,
    approved: true,
  },
  {
    id: "hill_accel_1",
    title: "Hill and resisted sprinting for acceleration development",
    authors: ["Seed Data"],
    publication: "AVA Seed Knowledge Base",
    year: 2017,
    journal: "Seed Data",
    sport: "athletics",
    population: { sex: "M", event: "100m", performanceLevel: "intermediate", sampleSize: 30, anthropometricNote: "collegiate sprinters" },
    studyType: "rct",
    quality: "moderate",
    keyFindings: ["Resisted and hill work associated with improved early acceleration."],
    limitations: ["Short intervention"],
    supportedMetrics: ["acceleration"],
    supportedInterventions: ["hillAccelerations", "resistedAccelerations"],
    supportedConclusions: ["Hill/resisted work commonly develops acceleration."],
    citation: "Seed Data (2017). AVA Seed Knowledge Base.",
    tags: { metrics: [], interventions: [], rootCauses: [], characteristics: [] },
    stanceByTarget: { hillAccelerations: "supporting", acceleration: "supporting" },
    sourceVersion: SEED,
    approved: true,
  },
  {
    id: "wicket_frontside_1",
    title: "Wicket runs and front-side sprint mechanics",
    authors: ["Seed Data"],
    publication: "AVA Seed Knowledge Base",
    year: 2016,
    journal: "Seed Data",
    sport: "athletics",
    population: { sex: "mixed", event: "sprint", performanceLevel: "advanced", sampleSize: 22, anthropometricNote: "sprinters" },
    studyType: "cross_sectional",
    quality: "limited",
    keyFindings: ["Wicket spacing associated with front-side mechanics cues."],
    limitations: ["Cross-sectional design"],
    supportedMetrics: ["strideFrequency", "strideLength"],
    supportedInterventions: ["wicketRuns"],
    supportedConclusions: ["Wickets commonly reinforce front-side mechanics."],
    citation: "Seed Data (2016). AVA Seed Knowledge Base.",
    tags: { metrics: [], interventions: [], rootCauses: [], characteristics: [] },
    stanceByTarget: { wicketRuns: "supporting" },
    sourceVersion: SEED,
    approved: true,
  },
  {
    id: "resisted_conflict_1",
    title: "Heavy resisted sprinting: mixed effects on top speed",
    authors: ["Seed Data"],
    publication: "AVA Seed Knowledge Base",
    year: 2022,
    journal: "Seed Data",
    sport: "athletics",
    population: { sex: "M", event: "100m", performanceLevel: "advanced", sampleSize: 18, anthropometricNote: "sprinters" },
    studyType: "rct",
    quality: "moderate",
    keyFindings: ["Very heavy resisted sprinting showed limited or negative transfer to top speed in some athletes."],
    limitations: ["Load-dependent"],
    supportedMetrics: ["peakVelocity"],
    supportedInterventions: ["resistedAccelerations"],
    supportedConclusions: ["Heavy loads may not transfer to top speed."],
    citation: "Seed Data (2022). AVA Seed Knowledge Base.",
    tags: { metrics: [], interventions: [], rootCauses: [], characteristics: [] },
    stanceByTarget: { resistedAccelerations: "conflicting" },
    sourceVersion: SEED,
    approved: true,
  },
  {
    id: "bounds_projection_1",
    title: "Bounding and horizontal power for projection",
    authors: ["Seed Data"],
    publication: "AVA Seed Knowledge Base",
    year: 2015,
    journal: "Seed Data",
    sport: "athletics",
    population: { sex: "mixed", event: "sprint", performanceLevel: "intermediate", sampleSize: 40, anthropometricNote: "trained athletes" },
    studyType: "cohort",
    quality: "moderate",
    keyFindings: ["Bounding associated with horizontal power and projection."],
    limitations: ["Transfer to sprinting not directly measured"],
    supportedMetrics: ["strideLength"],
    supportedInterventions: ["alternateBounds"],
    supportedConclusions: ["Bounds commonly develop projection."],
    citation: "Seed Data (2015). AVA Seed Knowledge Base.",
    tags: { metrics: [], interventions: [], rootCauses: [], characteristics: [] },
    stanceByTarget: { alternateBounds: "supporting" },
    sourceVersion: SEED,
    approved: true,
  },
];
