import { COACHING_RECOMMENDATION_MODEL_VERSION } from "@/lib/coachingRecommendations";
import { AUTHORITATIVE_METRIC_DEFINITIONS } from "./metricDefinitions";
import { formatReportNumber } from "./format";
import type { BuildSprintAnalysisReportInput, ReportMetric, ReportMetricKey, SprintAnalysisReport } from "./types";

export const ANALYSIS_REPORT_SCHEMA_VERSION = "ava-sprint-analysis-report-v1.0.0";
export const ANALYSIS_REPORT_TEMPLATE_VERSION = "ava-sprint-analysis-report-template-v1.0.0";
export const LIMITER_MODEL_VERSION = "limiting-factors-1.0.0";

const metricKeys = Object.keys(AUTHORITATIVE_METRIC_DEFINITIONS) as ReportMetricKey[];
const DISCLAIMER =
  "AVA Sprint analyzes movement and performance patterns from video. It does not diagnose injury, muscular weakness, medical conditions, or tissue capacity. Technical and physical associations require coach or qualified professional interpretation and may require additional testing.";

function metricInterpretation(key: ReportMetricKey, input: BuildSprintAnalysisReportInput): string {
  const related = input.limitingFactors.limiters.find((limiter) => {
    if (key.includes("step_length")) return limiter.type.includes("step_length");
    if (key === "step_frequency") return limiter.type.includes("step_frequency");
    return limiter.type.includes("velocity");
  });
  return related?.summary ?? "No validated comparison interpretation was available for this metric.";
}

function buildMetrics(input: BuildSprintAnalysisReportInput): ReportMetric[] {
  return metricKeys.map((key) => {
    const definition = AUTHORITATIVE_METRIC_DEFINITIONS[key];
    const value = input.metrics[key];
    return {
      key, name: definition.name, unit: definition.unit, value,
      formattedValue: formatReportNumber(value, definition.unit),
      definition: definition.definition,
      comparison: "No validated comparison target was available.",
      targetBasis: "Unavailable",
      confidence: value == null ? "Unavailable" : input.metricConfidence,
      interpretation: metricInterpretation(key, input),
    };
  });
}

export function buildSprintAnalysisReport(input: BuildSprintAnalysisReportInput): SprintAnalysisReport {
  const primary = input.sprintIntelligence.primaryConclusion;
  const strongest = input.sprintIntelligence.strengths[0];
  const topLimiter = input.limitingFactors.limiters[0];
  const asymmetric = input.limitingFactors.limiters.find((l) =>
    l.type === "step_length_asymmetry" || l.type === "step_frequency_asymmetry");
  const confidence = primary?.confidence ?? null;
  const coachDepth = input.audience !== "athlete";
  const branding = {
    organizationName: null, coachName: null, accentColor: "#2f80ed", footer: null,
    avaAttribution: "Generated by AVA Sprint",
    ...input.branding,
  };
  return {
    reportId: `${ANALYSIS_REPORT_SCHEMA_VERSION}:${input.analysisId}:${input.audience}`,
    analysisId: input.analysisId,
    sessionId: input.sessionId,
    athleteId: input.athleteId,
    audience: input.audience,
    lifecycleState: "ready",
    generatedAt: input.generatedAt,
    versions: {
      schema: ANALYSIS_REPORT_SCHEMA_VERSION,
      template: ANALYSIS_REPORT_TEMPLATE_VERSION,
      metricEngine: input.metricEngineVersion,
      limiterModel: input.limiterModelVersion,
      sprintIntelligence: input.sprintIntelligence.version,
      coachingRecommendations: input.coachingRecommendations.modelVersion || COACHING_RECOMMENDATION_MODEL_VERSION,
    },
    identity: {
      title: "Sprint Performance Analysis",
      subtitle: "Biomechanical Performance Summary",
      reference: `AVA-${input.analysisId.slice(0, 8).toUpperCase()}`,
    },
    athlete: structuredClone(input.athlete),
    session: structuredClone(input.session),
    executiveSummary: {
      primaryFinding: primary?.conciseSummary ?? input.limitingFactors.primaryConstraint ?? "No reliable primary limiter was identified.",
      performanceStrength: strongest?.conciseSummary ?? "No comparison-supported performance strength was available.",
      primaryTrainingDirection: input.coachingRecommendations.primaryDirection ?? "Preserve current mechanics and collect another compatible session.",
      confidenceLabel: confidence?.label.replaceAll("_", " ") ?? input.limitingFactors.overallDataQuality.replaceAll("_", " "),
      confidenceScore: confidence?.overall ?? null,
      importantContext: input.sprintIntelligence.missingInputs[0]?.wouldImprove ??
        input.limitingFactors.unavailableModels[0] ??
        "Interpret findings within the measured sprint context.",
    },
    metrics: buildMetrics(input),
    limitingFactors: structuredClone(input.limitingFactors.limiters),
    intelligence: {
      primary: structuredClone(primary),
      supporting: coachDepth ? structuredClone(input.sprintIntelligence.supportingConclusions) : [],
      assumptions: coachDepth ? structuredClone(input.sprintIntelligence.assumptions) : [],
      missingInputs: structuredClone(input.sprintIntelligence.missingInputs),
      changeConditions: coachDepth ? structuredClone(input.sprintIntelligence.changeConditions) : [],
      counterEvidence: coachDepth ? structuredClone(input.sprintIntelligence.counterEvidence) : [],
    },
    strengths: structuredClone(input.sprintIntelligence.strengths),
    asymmetry: asymmetric ? {
      title: asymmetric.title,
      measuredValues: structuredClone(asymmetric.measuredValues),
      percentage: asymmetric.deviation.percentage ?? null,
      confidence: asymmetric.confidence.label.replaceAll("_", " "),
      interpretation: asymmetric.summary,
      limitation: "AVA cannot determine whether this reflects strength, mobility, timing, pain, or normal variation from video alone.",
    } : null,
    recommendations: structuredClone(input.coachingRecommendations.recommendations.slice(0, 3)),
    monitoring: structuredClone(input.coachingRecommendations.monitoring.slice(0, 1)),
    additionalTesting: structuredClone(input.coachingRecommendations.assessments.slice(0, 1)),
    dataQuality: {
      measurementConfidence: confidence?.measurement ?? topLimiter?.confidence.measurement ?? null,
      reasoningConfidence: confidence?.reasoning ?? topLimiter?.confidence.reasoning ?? null,
      overallConfidence: confidence?.overall ?? topLimiter?.confidence.overall ?? null,
      calibrationConfirmed: input.sprintIntelligence.dataQuality.calibrationConfirmed,
      spatialAvailable: input.sprintIntelligence.dataQuality.spatialAvailable,
      validSteps: input.sprintIntelligence.dataQuality.validStepCount,
      warnings: [
        ...input.sprintIntelligence.dataQuality.notes,
        ...input.limitingFactors.limiters.flatMap((l) => l.dataQualityWarnings),
      ],
    },
    methodology: {
      metricsUsed: metricKeys.map((key) => AUTHORITATIVE_METRIC_DEFINITIONS[key].name),
      targetBasis: input.sprintIntelligence.methodology.targetBasisSummary,
      limiterRanking: input.sprintIntelligence.methodology.rankingBasis,
      confidenceBasis: input.sprintIntelligence.methodology.confidenceBasis,
      recommendationsBoundary: "Focused technical, sprint, assessment, and monitoring directions; no complete workout or rehabilitation plan.",
    },
    history: {
      available: false,
      summary: "Historical comparison will become available after additional compatible sessions are analyzed.",
    },
    branding,
    disclaimers: [DISCLAIMER, ...input.coachingRecommendations.limitations],
    sourceSnapshot: {
      limitingFactors: structuredClone(input.limitingFactors),
      sprintIntelligence: structuredClone(input.sprintIntelligence),
      coachingRecommendations: structuredClone(input.coachingRecommendations),
    },
  };
}
