/**
 * Intervention Library (Phase 7) — a structured, CONFIGURABLE database of training
 * interventions with educational metadata. Adding an intervention here makes it
 * automatically available to the matching engine. Every entry is educational
 * information (typical uses, distances, cues), NOT a prescription for the athlete.
 */

import type { Intervention, InterventionCategory } from "./models";

export const INTERVENTION_LIBRARY_VERSION = "ava-intervention-library-v1" as const;

export const INTERVENTION_CATEGORIES: InterventionCategory[] = [
  { id: "max_velocity", label: "Maximum Velocity", description: "Develops top-end speed mechanics and force at high velocity." },
  { id: "acceleration", label: "Acceleration", description: "Develops early horizontal force and acceleration posture." },
  { id: "plyometric", label: "Plyometric / Reactive", description: "Develops reactive strength, stiffness, and elastic return." },
  { id: "technical", label: "Technical", description: "Develops sprint mechanics, front-side action, and coordination." },
  { id: "strength_power", label: "Strength / Power", description: "Develops the force and power base underpinning sprinting." },
  { id: "mobility", label: "Mobility / Support", description: "Supports range of motion, foot/ankle function, and core control." },
];

const q = (...s: string[]) => s;

export const INTERVENTIONS: Intervention[] = [
  {
    id: "flyingSprints",
    name: "Flying Sprints",
    category: "max_velocity",
    primaryQualities: q("maximum velocity", "upright sprint mechanics"),
    secondaryQualities: q("relaxation", "rhythm", "stride length"),
    commonUses: q("developing top-end speed", "exposing the athlete to maximal velocity"),
    typicalLevel: ["intermediate", "advanced", "elite"],
    typicalPhase: q("max velocity development"),
    typicalDistances: "Typical fly zone 10–40 m after a 20–30 m build-up",
    typicalVolume: "Generally low volume",
    typicalRest: "Long, full recoveries between reps",
    coachingCues: q("stay tall and relaxed", "run through the zone", "let the ground come to you"),
    commonMistakes: q("over-striding", "tensing the upper body", "decelerating into the zone"),
    associatedMuscleGroups: q("hamstrings", "glutes", "calf complex"),
    evidenceStrength: "moderate",
    contraindications: q("acute hamstring sensitivity"),
    associatedMetrics: [
      { metricId: "peakVelocity", direction: "increase", kind: "direct" },
      { metricId: "strideLength", direction: "increase", kind: "direct" },
      { metricId: "groundContactTime", direction: "decrease", kind: "indirect" },
    ],
    rootCausesAddressed: q("frontSideMechanics", "projection", "reactiveStrength"),
    confidence: 0.6,
  },
  {
    id: "sprintFloatSprint",
    name: "Sprint-Float-Sprint",
    category: "max_velocity",
    primaryQualities: q("speed maintenance", "relaxation"),
    secondaryQualities: q("rhythm", "top-speed endurance"),
    commonUses: q("holding maximal velocity", "training relaxed top speed"),
    typicalLevel: ["intermediate", "advanced", "elite"],
    typicalPhase: q("max velocity", "speed endurance"),
    typicalDistances: "Accelerate, float, re-accelerate over ~60–80 m",
    typicalVolume: "Low to moderate volume",
    typicalRest: "Long recoveries",
    coachingCues: q("relax the float", "smooth transitions", "no visible gear change"),
    commonMistakes: q("tensing during the float", "changing posture between phases"),
    associatedMuscleGroups: q("hamstrings", "glutes"),
    evidenceStrength: "moderate",
    contraindications: q(),
    associatedMetrics: [
      { metricId: "maxVelocityMaintenance", direction: "increase", kind: "direct" },
      { metricId: "peakVelocity", direction: "increase", kind: "indirect" },
    ],
    rootCausesAddressed: q("frontSideMechanics", "fatigueIndicators"),
    confidence: 0.55,
  },
  {
    id: "hillAccelerations",
    name: "Hill Accelerations",
    category: "acceleration",
    primaryQualities: q("horizontal force", "acceleration posture", "projection"),
    secondaryQualities: q("force application"),
    commonUses: q("developing acceleration mechanics", "reinforcing shin angle"),
    typicalLevel: ["developing", "intermediate", "advanced"],
    typicalPhase: q("acceleration development", "general prep"),
    typicalDistances: "Typical distance 10–30 m on a moderate incline",
    typicalVolume: "Low to moderate",
    typicalRest: "Moderate to long recoveries",
    coachingCues: q("push the ground back", "gradual rise", "patient posture"),
    commonMistakes: q("standing up too early", "over-striding uphill"),
    associatedMuscleGroups: q("glutes", "quadriceps", "calves"),
    evidenceStrength: "moderate",
    contraindications: q("calf/Achilles sensitivity"),
    associatedMetrics: [
      { metricId: "acceleration", direction: "increase", kind: "direct" },
      { metricId: "peakVelocity", direction: "increase", kind: "indirect" },
    ],
    rootCausesAddressed: q("verticalForce", "hipExtensionTiming", "projection"),
    confidence: 0.5,
  },
  {
    id: "resistedAccelerations",
    name: "Resisted Accelerations",
    category: "acceleration",
    primaryQualities: q("horizontal force", "acceleration strength"),
    secondaryQualities: q("posture"),
    commonUses: q("increasing early horizontal force"),
    typicalLevel: ["intermediate", "advanced", "elite"],
    typicalPhase: q("acceleration development"),
    typicalDistances: "Typically 10–20 m with light-to-moderate resistance",
    typicalVolume: "Low volume",
    typicalRest: "Long recoveries",
    coachingCues: q("aggressive push", "hold the angle"),
    commonMistakes: q("resistance too heavy (posture collapses)"),
    associatedMuscleGroups: q("glutes", "quadriceps", "calves"),
    evidenceStrength: "moderate",
    contraindications: q(),
    associatedMetrics: [{ metricId: "acceleration", direction: "increase", kind: "direct" }],
    rootCausesAddressed: q("verticalForce", "hipExtensionTiming"),
    confidence: 0.5,
  },
  {
    id: "assistedSprinting",
    name: "Assisted Sprinting",
    category: "max_velocity",
    primaryQualities: q("over-speed turnover", "leg speed"),
    secondaryQualities: q("front-side recovery"),
    commonUses: q("exposing the nervous system to higher turnover"),
    typicalLevel: ["advanced", "elite"],
    typicalPhase: q("max velocity"),
    typicalDistances: "Short over-speed zones with light assistance",
    typicalVolume: "Very low volume",
    typicalRest: "Full recoveries",
    coachingCues: q("stay relaxed", "keep front-side mechanics"),
    commonMistakes: q("over-assistance disrupting mechanics"),
    associatedMuscleGroups: q("hip flexors", "hamstrings"),
    evidenceStrength: "limited",
    contraindications: q("hamstring sensitivity"),
    associatedMetrics: [{ metricId: "strideFrequency", direction: "increase", kind: "direct" }],
    rootCausesAddressed: q("frontSideMechanics"),
    confidence: 0.4,
  },
  {
    id: "wicketRuns",
    name: "Wicket Runs",
    category: "technical",
    primaryQualities: q("front-side mechanics", "stride rhythm"),
    secondaryQualities: q("stride length", "posture"),
    commonUses: q("grooving upright mechanics", "rhythm at speed"),
    typicalLevel: ["developing", "intermediate", "advanced"],
    typicalPhase: q("technical", "max velocity"),
    typicalDistances: "Individualized wicket spacing over 20–40 m",
    typicalVolume: "Low to moderate",
    typicalRest: "Moderate recoveries",
    coachingCues: q("step over the wicket", "tall posture", "let rhythm build"),
    commonMistakes: q("reaching for wickets", "spacing that forces overstriding"),
    associatedMuscleGroups: q("hip flexors", "core"),
    evidenceStrength: "moderate",
    contraindications: q(),
    associatedMetrics: [
      { metricId: "strideFrequency", direction: "increase", kind: "direct" },
      { metricId: "strideLength", direction: "increase", kind: "direct" },
    ],
    rootCausesAddressed: q("frontSideMechanics", "groundStrikePosition", "timingCoordination"),
    confidence: 0.55,
  },
  {
    id: "straightLegBounds",
    name: "Straight-Leg Bounds",
    category: "plyometric",
    primaryQualities: q("stiffness", "ground return"),
    secondaryQualities: q("stride frequency"),
    commonUses: q("developing turnover and stiffness"),
    typicalLevel: ["intermediate", "advanced"],
    typicalPhase: q("plyometric", "general prep"),
    typicalDistances: "20–30 m of continuous stiff bounding",
    typicalVolume: "Low to moderate",
    typicalRest: "Moderate recoveries",
    coachingCues: q("stiff ankles", "paw the ground", "minimal contact"),
    commonMistakes: q("soft, collapsing contacts", "bending the knee"),
    associatedMuscleGroups: q("calf complex", "hamstrings"),
    evidenceStrength: "moderate",
    contraindications: q("Achilles sensitivity"),
    associatedMetrics: [
      { metricId: "strideFrequency", direction: "increase", kind: "direct" },
      { metricId: "groundContactTime", direction: "decrease", kind: "direct" },
    ],
    rootCausesAddressed: q("elasticStiffness", "reactiveStrength"),
    confidence: 0.5,
  },
  {
    id: "alternateBounds",
    name: "Alternate-leg Bounds",
    category: "plyometric",
    primaryQualities: q("horizontal power", "projection"),
    secondaryQualities: q("stride length"),
    commonUses: q("developing projection and horizontal power"),
    typicalLevel: ["intermediate", "advanced"],
    typicalPhase: q("plyometric"),
    typicalDistances: "20–40 m of alternate bounds for distance",
    typicalVolume: "Low volume",
    typicalRest: "Moderate to long recoveries",
    coachingCues: q("cover ground", "drive and project", "rhythmic"),
    commonMistakes: q("bounding for height instead of distance"),
    associatedMuscleGroups: q("glutes", "hamstrings", "calves"),
    evidenceStrength: "moderate",
    contraindications: q(),
    associatedMetrics: [
      { metricId: "strideLength", direction: "increase", kind: "direct" },
      { metricId: "peakVelocity", direction: "increase", kind: "indirect" },
    ],
    rootCausesAddressed: q("projection", "verticalForce"),
    confidence: 0.5,
  },
  {
    id: "pogoSeries",
    name: "Pogo Series",
    category: "plyometric",
    primaryQualities: q("reactive strength", "ankle stiffness"),
    secondaryQualities: q("elastic return"),
    commonUses: q("developing short, forceful contacts"),
    typicalLevel: ["developing", "intermediate", "advanced"],
    typicalPhase: q("plyometric", "general prep"),
    typicalDistances: "Short pogo sets in place or moving",
    typicalVolume: "Low to moderate",
    typicalRest: "Short-to-moderate recoveries",
    coachingCues: q("minimal ground time", "stiff ankles", "quiet contacts"),
    commonMistakes: q("bending the knees", "long, soft contacts"),
    associatedMuscleGroups: q("calf complex", "foot/ankle complex"),
    evidenceStrength: "moderate",
    contraindications: q("Achilles/calf sensitivity"),
    associatedMetrics: [{ metricId: "groundContactTime", direction: "decrease", kind: "direct" }],
    rootCausesAddressed: q("reactiveStrength", "elasticStiffness"),
    confidence: 0.55,
  },
  {
    id: "depthJumps",
    name: "Depth Jumps",
    category: "plyometric",
    primaryQualities: q("reactive strength"),
    secondaryQualities: q("stiffness"),
    commonUses: q("developing high-intensity reactive strength"),
    typicalLevel: ["advanced", "elite"],
    typicalPhase: q("plyometric (advanced)"),
    typicalDistances: "Moderate drop heights",
    typicalVolume: "Very low volume",
    typicalRest: "Long recoveries",
    coachingCues: q("minimal contact", "explode up"),
    commonMistakes: q("excessive drop height", "long ground contact"),
    associatedMuscleGroups: q("quadriceps", "calf complex"),
    evidenceStrength: "moderate",
    contraindications: q("insufficient strength base", "knee sensitivity"),
    associatedMetrics: [{ metricId: "groundContactTime", direction: "decrease", kind: "direct" }],
    rootCausesAddressed: q("reactiveStrength"),
    confidence: 0.5,
  },
  {
    id: "dropJumps",
    name: "Drop Jumps",
    category: "plyometric",
    primaryQualities: q("reactive strength index"),
    secondaryQualities: q("stiffness"),
    commonUses: q("developing and monitoring reactive strength"),
    typicalLevel: ["advanced", "elite"],
    typicalPhase: q("plyometric (advanced)"),
    typicalDistances: "Standardized drop heights",
    typicalVolume: "Very low volume",
    typicalRest: "Long recoveries",
    coachingCues: q("short contact", "spring off"),
    commonMistakes: q("prioritizing height over contact time"),
    associatedMuscleGroups: q("calf complex", "quadriceps"),
    evidenceStrength: "moderate",
    contraindications: q("insufficient strength base"),
    associatedMetrics: [{ metricId: "groundContactTime", direction: "decrease", kind: "direct" }],
    rootCausesAddressed: q("reactiveStrength", "elasticStiffness"),
    confidence: 0.5,
  },
  {
    id: "wallDrills",
    name: "Wall Drills",
    category: "technical",
    primaryQualities: q("front-side mechanics", "posture"),
    secondaryQualities: q("timing"),
    commonUses: q("isolating front-side action and posture"),
    typicalLevel: ["developing", "intermediate"],
    typicalPhase: q("technical", "general prep"),
    typicalDistances: "In place at a wall",
    typicalVolume: "Low volume",
    typicalRest: "Short recoveries",
    coachingCues: q("tall posture", "front-side action", "sharp switch"),
    commonMistakes: q("leaning too far", "reaching back-side"),
    associatedMuscleGroups: q("hip flexors", "core"),
    evidenceStrength: "limited",
    contraindications: q(),
    associatedMetrics: [{ metricId: "strideFrequency", direction: "increase", kind: "indirect" }],
    rootCausesAddressed: q("frontSideMechanics", "timingCoordination"),
    confidence: 0.4,
  },
  {
    id: "aSkips",
    name: "A-Skips",
    category: "technical",
    primaryQualities: q("front-side mechanics", "rhythm"),
    secondaryQualities: q("coordination"),
    commonUses: q("grooving knee drive and ground return"),
    typicalLevel: ["developing", "intermediate"],
    typicalPhase: q("technical", "warm-up"),
    typicalDistances: "20–30 m",
    typicalVolume: "Low to moderate",
    typicalRest: "Short recoveries",
    coachingCues: q("tall", "front-side", "rhythmic"),
    commonMistakes: q("back-side reaching", "collapsing posture"),
    associatedMuscleGroups: q("hip flexors", "calf complex"),
    evidenceStrength: "limited",
    contraindications: q(),
    associatedMetrics: [{ metricId: "strideFrequency", direction: "increase", kind: "indirect" }],
    rootCausesAddressed: q("frontSideMechanics", "timingCoordination"),
    confidence: 0.4,
  },
  {
    id: "bSkips",
    name: "B-Skips",
    category: "technical",
    primaryQualities: q("ground preparation", "hamstring action"),
    secondaryQualities: q("coordination"),
    commonUses: q("grooving active touchdown"),
    typicalLevel: ["intermediate", "advanced"],
    typicalPhase: q("technical"),
    typicalDistances: "20–30 m",
    typicalVolume: "Low volume",
    typicalRest: "Short recoveries",
    coachingCues: q("paw back", "active touchdown"),
    commonMistakes: q("over-reaching the leg"),
    associatedMuscleGroups: q("hamstrings", "glutes"),
    evidenceStrength: "limited",
    contraindications: q("hamstring sensitivity"),
    associatedMetrics: [{ metricId: "groundStrikePosition" as string, direction: "increase", kind: "indirect" }],
    rootCausesAddressed: q("groundStrikePosition", "technicalOverreaching"),
    confidence: 0.4,
  },
  {
    id: "dribbleProgressions",
    name: "Dribble Progressions",
    category: "technical",
    primaryQualities: q("ground return", "front-side recovery"),
    secondaryQualities: q("frequency"),
    commonUses: q("developing quick ground return into acceleration"),
    typicalLevel: ["developing", "intermediate"],
    typicalPhase: q("technical", "acceleration"),
    typicalDistances: "Ankle/knee dribbles into 10–20 m acceleration",
    typicalVolume: "Low to moderate",
    typicalRest: "Short recoveries",
    coachingCues: q("quick ground return", "gradual build"),
    commonMistakes: q("reaching", "loss of posture on transition"),
    associatedMuscleGroups: q("hip flexors", "calf complex"),
    evidenceStrength: "limited",
    contraindications: q(),
    associatedMetrics: [{ metricId: "strideFrequency", direction: "increase", kind: "direct" }],
    rootCausesAddressed: q("frontSideMechanics", "timingCoordination"),
    confidence: 0.4,
  },
  {
    id: "switchDrills",
    name: "Switch Drills",
    category: "technical",
    primaryQualities: q("limb switching", "recovery timing"),
    secondaryQualities: q("coordination"),
    commonUses: q("improving inter-limb switching and timing"),
    typicalLevel: ["intermediate", "advanced"],
    typicalPhase: q("technical"),
    typicalDistances: "In place or short distances",
    typicalVolume: "Low volume",
    typicalRest: "Short recoveries",
    coachingCues: q("sharp switch", "front-side"),
    commonMistakes: q("slow, late switch"),
    associatedMuscleGroups: q("hip flexors", "core"),
    evidenceStrength: "limited",
    contraindications: q(),
    associatedMetrics: [{ metricId: "strideFrequency", direction: "increase", kind: "indirect" }],
    rootCausesAddressed: q("timingCoordination", "delayedRecovery", "frontSideMechanics"),
    confidence: 0.4,
  },
  {
    id: "medicineBallThrows",
    name: "Medicine Ball Throws",
    category: "strength_power",
    primaryQualities: q("power expression", "horizontal force"),
    secondaryQualities: q("core"),
    commonUses: q("developing rapid force expression"),
    typicalLevel: ["developing", "intermediate", "advanced"],
    typicalPhase: q("power", "general prep"),
    typicalDistances: "Throws for distance",
    typicalVolume: "Low to moderate",
    typicalRest: "Moderate recoveries",
    coachingCues: q("explosive intent", "full extension"),
    commonMistakes: q("submaximal intent"),
    associatedMuscleGroups: q("glutes", "core", "posterior chain"),
    evidenceStrength: "limited",
    contraindications: q(),
    associatedMetrics: [{ metricId: "acceleration", direction: "increase", kind: "indirect" }],
    rootCausesAddressed: q("verticalForce", "hipExtensionTiming"),
    confidence: 0.4,
  },
  {
    id: "hipProjectionDrills",
    name: "Hip Projection Drills",
    category: "technical",
    primaryQualities: q("projection", "hip extension timing"),
    secondaryQualities: q("stride length"),
    commonUses: q("developing projection off the ground"),
    typicalLevel: ["intermediate", "advanced"],
    typicalPhase: q("technical"),
    typicalDistances: "Short technical distances",
    typicalVolume: "Low volume",
    typicalRest: "Short-to-moderate recoveries",
    coachingCues: q("project, don't reach", "extend through the hip"),
    commonMistakes: q("reaching for stride length (overstriding)"),
    associatedMuscleGroups: q("glutes", "hamstrings"),
    evidenceStrength: "limited",
    contraindications: q(),
    associatedMetrics: [{ metricId: "strideLength", direction: "increase", kind: "direct" }],
    rootCausesAddressed: q("projection", "hipExtensionTiming"),
    confidence: 0.45,
  },
  {
    id: "mobilityFocus",
    name: "Mobility Focus",
    category: "mobility",
    primaryQualities: q("range of motion"),
    secondaryQualities: q("posture", "recovery"),
    commonUses: q("addressing mobility restrictions associated with the pattern"),
    typicalLevel: ["developing", "intermediate", "advanced", "elite"],
    typicalPhase: q("all phases", "warm-up/cool-down"),
    typicalDistances: "n/a",
    typicalVolume: "Low volume, frequent",
    typicalRest: "n/a",
    coachingCues: q("controlled range", "no forcing"),
    commonMistakes: q("aggressive static stretching pre-sprint"),
    associatedMuscleGroups: q("hip flexors", "adductors", "foot/ankle complex"),
    evidenceStrength: "limited",
    contraindications: q(),
    associatedMetrics: [{ metricId: "strideLength", direction: "increase", kind: "indirect" }],
    rootCausesAddressed: q("mobilityRestriction"),
    confidence: 0.4,
  },
  {
    id: "footAnkleStiffness",
    name: "Foot & Ankle Stiffness",
    category: "mobility",
    primaryQualities: q("foot/ankle stiffness"),
    secondaryQualities: q("reactive strength"),
    commonUses: q("developing a stiffer, more elastic foot/ankle"),
    typicalLevel: ["developing", "intermediate", "advanced"],
    typicalPhase: q("general prep", "warm-up"),
    typicalDistances: "In place / short",
    typicalVolume: "Low volume",
    typicalRest: "Short recoveries",
    coachingCues: q("stiff ankle", "quick off the ground"),
    commonMistakes: q("soft, slow contacts"),
    associatedMuscleGroups: q("foot/ankle complex", "soleus", "gastrocnemius"),
    evidenceStrength: "limited",
    contraindications: q("acute foot pain"),
    associatedMetrics: [{ metricId: "groundContactTime", direction: "decrease", kind: "direct" }],
    rootCausesAddressed: q("elasticStiffness", "reactiveStrength"),
    confidence: 0.45,
  },
  {
    id: "coreStability",
    name: "Core Stability",
    category: "mobility",
    primaryQualities: q("trunk control", "posture"),
    secondaryQualities: q("force transfer"),
    commonUses: q("supporting posture and force transfer"),
    typicalLevel: ["developing", "intermediate", "advanced", "elite"],
    typicalPhase: q("all phases"),
    typicalDistances: "n/a",
    typicalVolume: "Low to moderate",
    typicalRest: "Short recoveries",
    coachingCues: q("brace", "maintain posture"),
    commonMistakes: q("holding the breath", "excessive volume"),
    associatedMuscleGroups: q("core"),
    evidenceStrength: "limited",
    contraindications: q(),
    associatedMetrics: [{ metricId: "strideFrequency", direction: "increase", kind: "indirect" }],
    rootCausesAddressed: q("timingCoordination"),
    confidence: 0.35,
  },
];

export function intervention(id: string): Intervention | undefined {
  return INTERVENTIONS.find((i) => i.id === id);
}
export function interventionCategory(id: string): InterventionCategory | undefined {
  return INTERVENTION_CATEGORIES.find((c) => c.id === id);
}
