import { SCIENTIFIC_VALIDATION_VERSION,metricValidationEntrySchema,type MetricValidationEntry } from "./contracts";
const entry=(value:Omit<MetricValidationEntry,"registryVersion">)=>metricValidationEntrySchema.parse({...value,registryVersion:SCIENTIFIC_VALIDATION_VERSION});
export const METRIC_VALIDATION_REGISTRY:readonly MetricValidationEntry[]=Object.freeze([
  entry({metricId:"zone_time_s",displayName:"Zone time",validationClass:"direct_timing_measurement",definition:"Elapsed time between confirmed physical zone crossings.",unit:"s",computation:"Timestamp difference between start and finish boundary crossings.",dependencies:["confirmed gates","source timestamps"],requiredConditions:["60 FPS-class or higher","compatible start/finish definition","confirmed calibration"],supportedFps:["60_class","120","240"],expectedError:"Not established on a locked reference dataset.",confidencePolicy:"Withhold on ambiguous crossing or incompatible timing definition.",referenceMethod:"Synchronized timing gates or adjudicated high-speed frame boundaries.",validationStatus:"partially_validated",defaultVisibility:"coach_only",minimumConfidence:.7,manualReviewTriggers:["boundary ambiguity","high-value competition"],limitations:["Existing real fixture has an incomplete reference definition."]}),
  entry({metricId:"average_velocity_mps",displayName:"Average zone velocity",validationClass:"derived_performance_metric",definition:"Zone distance divided by compatible zone time.",unit:"m/s",computation:"calibrated distance / zone time",dependencies:["zone_time_s","calibrated zone distance"],requiredConditions:["static validated calibration","compatible timing"],supportedFps:["60_class","120","240"],expectedError:"Inherits timing and calibration error; not quantified on locked data.",confidencePolicy:"Never exceed weakest dependency confidence.",referenceMethod:"Measured distance divided by synchronized reference time.",validationStatus:"partially_validated",defaultVisibility:"coach_only",minimumConfidence:.7,manualReviewTriggers:["calibration uncertainty"],limitations:["Panning spatial calibration is withheld."]}),
  entry({metricId:"step_frequency_hz",displayName:"Combined step frequency",validationClass:"temporal_estimate",definition:"Combined contact cadence across the analyzed interval.",unit:"Hz",computation:"Detected contact sequence over compatible elapsed interval.",dependencies:["contact events","timestamps"],requiredConditions:["reliable foot events","single athlete"],supportedFps:["60_class","120","240"],expectedError:"Not quantified against dual-reviewed contacts.",confidencePolicy:"Withhold when foot-event trust is below threshold.",referenceMethod:"Dual-reviewer high-speed contact annotations.",validationStatus:"fixture_validated",defaultVisibility:"visible_with_confidence_warning",minimumConfidence:.7,manualReviewTriggers:["occlusion","duplicate contacts"],limitations:["Left/right asymmetry is not approved."]}),
  entry({metricId:"average_step_length_m",displayName:"Average step length",validationClass:"spatial_measurement",definition:"Average calibrated track-plane distance between opposite-foot contacts.",unit:"m",computation:"World-plane contact displacement.",dependencies:["contact events","calibration","camera stability"],requiredConditions:["static calibration","visible contacts"],supportedFps:["60_class","120","240"],expectedError:"No locked tape-grid estimate.",confidencePolicy:"Withhold for smooth pan, zoom, unreliable calibration or tracking.",referenceMethod:"Tape-grid or surveyed contact positions.",validationStatus:"partially_validated",defaultVisibility:"coach_only",minimumConfidence:.75,manualReviewTriggers:["boundary partial step","calibration ambiguity"],limitations:["Per-side placement bias observed in development diagnostics."]}),
  entry({metricId:"ground_contact_time_ms",displayName:"Ground contact estimate",validationClass:"temporal_estimate",definition:"Frame/timestamp-derived interval from contact to toe-off.",unit:"ms",computation:"Detected contact-to-toe-off interval.",dependencies:["contact event","toe-off event","timestamps"],requiredConditions:["unoccluded foot","reliable event detection"],supportedFps:["60_class","120","240"],expectedError:"60 FPS quantization alone is approximately 16.7 ms per frame; reference error unquantified.",confidencePolicy:"Experimental until reference agreement and FPS visibility bands are established.",referenceMethod:"Force/pressure system or adjudicated high-speed annotation.",validationStatus:"unvalidated",defaultVisibility:"experimental",minimumConfidence:null,manualReviewTriggers:["all athlete-facing use"],limitations:["Not approved as a precise athlete-facing value."]}),
  entry({metricId:"flight_time_ms",displayName:"Flight-time estimate",validationClass:"temporal_estimate",definition:"Frame/timestamp-derived interval between toe-off and next contact.",unit:"ms",computation:"Detected toe-off-to-contact interval.",dependencies:["toe-off event","next contact","timestamps"],requiredConditions:["unoccluded feet","reliable consecutive events"],supportedFps:["60_class","120","240"],expectedError:"60 FPS quantization alone is approximately 16.7 ms per frame; reference error unquantified.",confidencePolicy:"Experimental until reference agreement and FPS visibility bands are established.",referenceMethod:"Force/pressure system or adjudicated high-speed annotation.",validationStatus:"unvalidated",defaultVisibility:"experimental",minimumConfidence:null,manualReviewTriggers:["all athlete-facing use"],limitations:["Not approved as a precise athlete-facing value."]}),
  entry({metricId:"peak_knee_flexion_deg",displayName:"Peak knee-flexion estimate",validationClass:"kinematic_estimate",definition:"Maximum modeled knee flexion from 2D pose.",unit:"deg",computation:"180 degrees minus minimum modeled interior knee angle.",dependencies:["pose landmarks","camera view"],requiredConditions:["side view","visible hip/knee/ankle"],supportedFps:["60_class","120","240"],expectedError:"No anatomical reference study.",confidencePolicy:"Technique context only; never diagnostic.",referenceMethod:"Synchronized marker-based or independently annotated kinematics.",validationStatus:"unvalidated",defaultVisibility:"coach_only",minimumConfidence:.7,manualReviewTriggers:["occlusion","left-right swap"],limitations:["2D pose is not anatomical ground truth."]}),
  entry({metricId:"trunk_lean_deg",displayName:"Trunk-lean estimate",validationClass:"kinematic_estimate",definition:"2D shoulder-to-hip segment angle.",unit:"deg",computation:"Pose segment orientation in image coordinates.",dependencies:["shoulder/hip landmarks","camera alignment"],requiredConditions:["side view","stable camera"],supportedFps:["60_class","120","240"],expectedError:"No anatomical reference study.",confidencePolicy:"Visible with coach context only when pose and camera trust pass.",referenceMethod:"Marker-based kinematics or blinded expert annotation.",validationStatus:"unvalidated",defaultVisibility:"coach_only",minimumConfidence:.7,manualReviewTriggers:["camera misalignment"],limitations:["Camera perspective can bias angle."]}),
  entry({metricId:"top_speed_mps",displayName:"Peak velocity",validationClass:"derived_performance_metric",definition:"Peak compatible velocity estimate.",unit:"m/s",computation:"Versioned velocity profile.",dependencies:["spatial calibration","timing","smoothing definition"],requiredConditions:["validated static calibration","compatible reference definition"],supportedFps:["60_class","120","240"],expectedError:"Not established.",confidencePolicy:"Hidden until peak definition and reference study are locked.",referenceMethod:"Compatible radar/laser or zone timing definition.",validationStatus:"hidden",defaultVisibility:"hidden",minimumConfidence:null,manualReviewTriggers:["all use"],limitations:["Instantaneous precision is unsupported at insufficient resolution."]}),
  entry({metricId:"root_cause_hypothesis",displayName:"Likely movement explanation",validationClass:"interpretive_coaching_output",definition:"Evidence-linked possible limiter hypothesis.",unit:"classification",computation:"Deterministic versioned evidence rules.",dependencies:["validated observations","interpretations","history"],requiredConditions:["qualified association language","alternatives","confidence"],supportedFps:["60_class","120","240"],expectedError:"Coach agreement not measured.",confidencePolicy:"Possible/supported language only; no diagnosis.",referenceMethod:"Blinded qualified coach rubric.",validationStatus:"unvalidated",defaultVisibility:"coach_only",minimumConfidence:null,manualReviewTriggers:["high-impact recommendation"],limitations:["Footage cannot establish strength, injury or causation."]}),
  entry({metricId:"performance_projection",displayName:"Performance projection",validationClass:"predictive_output",definition:"Evidence-bounded scenario projection, not a promised result.",unit:"metric-specific",computation:"Deterministic projection engine with assumptions and unknowns.",dependencies:["compatible history","benchmark version","evidence"],requiredConditions:["uncertainty interval","supported target population"],supportedFps:["60_class","120","240"],expectedError:"No outcome validation dataset.",confidencePolicy:"Withhold precise prediction; label intervals evidence-bounded and uncalibrated.",referenceMethod:"Prospective held-out outcomes.",validationStatus:"unvalidated",defaultVisibility:"experimental",minimumConfidence:null,manualReviewTriggers:["all athlete-facing use"],limitations:["PB/race-time synthesis is explicitly unsupported."]}),
]);
const byId=new Map(METRIC_VALIDATION_REGISTRY.map(x=>[x.metricId,x]));
export function metricValidationEntry(metricId:string){const value=byId.get(metricId);if(!value)throw new Error(`unregistered_metric:${metricId}`);return value;}
export function resolveMetricVisibility(metricId:string,input:{fpsClass:"unsupported"|"60_class"|"120"|"240";confidence:number|null;manualReview:boolean}){
  const metric=metricValidationEntry(metricId);
  if(input.fpsClass==="unsupported"||!metric.supportedFps.includes(input.fpsClass as never))return{visibility:"hidden",reasonCodes:["unsupported_fps"]};
  if(["hidden","removed"].includes(metric.defaultVisibility))return{visibility:metric.defaultVisibility,reasonCodes:["registry_policy"]};
  if(metric.minimumConfidence!=null&&(input.confidence==null||input.confidence<metric.minimumConfidence))return{visibility:"hidden",reasonCodes:["confidence_below_policy"]};
  if(metric.manualReviewTriggers.length&&input.manualReview)return{visibility:"coach_only",reasonCodes:["manual_review_required"]};
  return{visibility:metric.defaultVisibility,reasonCodes:[]};
}

